server:
  port: 9090

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  thymeleaf:
    cache: false